# define a default docker image for all jobs
# from https://github.com/trek10inc/gitlab-boilerplate-injector/blob/master/.gitlab-ci.yml
image: node:latest

variables:
    PROJECT: "kaamelottvoices"

stages:
    - install # install all npm dependencies
    - test    # execute unit tests
    - deploy  # stage for deploying


npmInstall:
    stage: install
    script:
        - npm install
    # artifacts describe the result of the stage
    # that can be used in consecutive stages
    artifacts:
        untracked: true


#linting:
#    stage: test
#    script:
#        # install standardjs for linting
#        - npm install -g standard
#        - npm run-script lint

deploy:prod-skill:
  stage: deploy
  dependencies:
    - npmInstall
  script:
    - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - npm install -g serverless@1.36.3
    - ls
#    - mv build .build
    - sls deploy -v -s prod --region ${REGION:-"eu-west-1"} -f skill
  when: manual
  only:
  - master
deploy:prod-home:
  stage: deploy
  dependencies:
    - npmInstall
  script:
    - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - npm install -g serverless@1.36.3
    - ls
#    - mv build .build
    - sls deploy -v -s prod --region ${REGION:-"eu-west-1"} -f home
  when: manual
  only:
  - master
  
deploy:prod:
  stage: deploy
  dependencies:
    - npmInstall
  script:
    - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - npm install -g serverless@1.36.3
    - ls
#    - mv build .build
    - sls deploy -v -s prod --region ${REGION:-"eu-west-1"}
  when: manual
  only:
  - master
  
unittesting:
    stage: test
    # use the artifcats of the 'npmInstall' job
    dependencies:
        - npmInstall
    script:
        # install dev-dependency mocha
        - npm test
